"""11th revision

Revision ID: 2808391b669e
Revises: 82443ac5175b
Create Date: 2022-09-18 17:39:41.532519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2808391b669e'
down_revision = '82443ac5175b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
