"""6th revision

Revision ID: 77185e0d8882
Revises: 3ac58b70cd7e
Create Date: 2022-09-08 22:38:09.609749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77185e0d8882'
down_revision = '3ac58b70cd7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
