"""11th revision

Revision ID: 82443ac5175b
Revises: dba8b6e2fcea
Create Date: 2022-09-18 16:59:39.995146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82443ac5175b'
down_revision = 'dba8b6e2fcea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
