"""10th revision

Revision ID: dba8b6e2fcea
Revises: 110795784250
Create Date: 2022-09-18 16:56:02.627927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba8b6e2fcea'
down_revision = '110795784250'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
