"""2nd revision

Revision ID: e04dbef7e76c
Revises: 33318060f2fe
Create Date: 2022-09-03 00:42:21.245570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04dbef7e76c'
down_revision = '33318060f2fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
